title: GameMakerHow
author: Gurpreet Singh Matharoo
email: gurpreetsingh793@gmail.com
description: >
  Your GameMaker Questions, Answered

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      contributor: matharoo


header_pages:
- search.md
- posts.md
- categories.md
- contribute.md

footer_icons:
- username: Gurpreet S. Matharoo
  url: https://twitter.com/itsmatharoo
  icon: Twitter-Logo.svg

paginate: 20

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec